replicaCount: 2
image:
  repository: node-hello
  tag: v5
service:
  type: NodePort
  port: 80
ingress:
  enabled: true
  host: hello-world.local
htttpRoute:
  enabled: false
mongodb:
  service: mongodb-service
  port: 27017
  database: myapp
